/* Generated by the Nim Compiler v2.0.8 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI553648134 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
var NTI553648132 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI553648133 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
var NTI771752005 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33555179 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217746 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI1124073475 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554448 = {size: 0,kind: 2,base: null,node: null,finalizer: null};
var NTI1124073476 = {size: 0, kind: 19, base: null, node: null, finalizer: null};
var NTI134217745 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217742 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI553648131 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33554466 = {size: 0,kind: 1,base: null,node: null,finalizer: null};
var NTI33554435 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI704643086 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI134217749 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217751 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555173 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555181 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554449 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NTI33554450 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33555180 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555177 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555178 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217741 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217743 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NNI134217743 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217743.node = NNI134217743;
var NNI134217741 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217741.node = NNI134217741;
var NNI33555178 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555178.node = NNI33555178;
NTI33555180.base = NTI33555177;
NTI33555181.base = NTI33555177;
var NNI33555177 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555180, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI33554450, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI33554449, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI33554449, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI33555181, name: "up", sons: null}]};
NTI33555177.node = NNI33555177;
var NNI33555173 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555173.node = NNI33555173;
NTI33555177.base = NTI33555173;
NTI33555178.base = NTI33555177;
NTI134217741.base = NTI33555178;
NTI134217743.base = NTI134217741;
var NNI134217751 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217751.node = NNI134217751;
NTI134217751.base = NTI33555178;
var NNI134217749 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217749.node = NNI134217749;
NTI134217749.base = NTI33555178;
var NNI704643086 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554435, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554466, name: "Field1", sons: null}]};
NTI704643086.node = NNI704643086;
var NNI553648131 = {kind: 2, len: 4, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "element", len: 0, typ: NTI33554449, name: "element", sons: null}, 
{kind: 1, offset: "slug", len: 0, typ: NTI33554449, name: "slug", sons: null}, 
{kind: 1, offset: "count", len: 0, typ: NTI33554435, name: "count", sons: null}, 
{kind: 1, offset: "score", len: 0, typ: NTI33554435, name: "score", sons: null}]};
NTI553648131.node = NNI553648131;
var NNI134217742 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217742.node = NNI134217742;
NTI134217742.base = NTI134217741;
var NNI134217745 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217745.node = NNI134217745;
NTI134217745.base = NTI33555178;
NTI1124073476.base = NTI33554448;
var NNI1124073475 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI1124073475.node = NNI1124073475;
var NNI134217746 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217746.node = NNI134217746;
var NNI33555179 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555179.node = NNI33555179;
NTI33555179.base = NTI33555177;
NTI134217746.base = NTI33555179;
NTI1124073475.base = NTI134217746;
var NNI771752005 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "a", len: 0, typ: NTI33554435, name: "a", sons: null}, 
{kind: 1, offset: "b", len: 0, typ: NTI33554435, name: "b", sons: null}]};
NTI771752005.node = NNI771752005;
NTI553648133.base = NTI33554449;
var NNI553648132 = {kind: 2, len: 4, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "title", len: 0, typ: NTI33554449, name: "title", sons: null}, 
{kind: 1, offset: "slug", len: 0, typ: NTI33554449, name: "slug", sons: null}, 
{kind: 1, offset: "contentTokens", len: 0, typ: NTI553648133, name: "contentTokens", sons: null}, 
{kind: 1, offset: "displayContent", len: 0, typ: NTI33554449, name: "displayContent", sons: null}]};
NTI553648132.node = NNI553648132;
NTI553648134.base = NTI553648132;

function mnewString(len_33557003) {
        var result = new Array(len_33557003);
    for (var i = 0; i < len_33557003; i++) {result[i] = 0;}
    return result;
  

  
}

function toJSStr(s_33556901) {
  var result_33556902 = null;

    var res_33556943 = newSeq_33556919((s_33556901).length);
    var i_33556944 = 0;
    var j_33556945 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33556944 < (s_33556901).length)) break Label2;
          var c_33556946 = s_33556901[i_33556944];
          if ((c_33556946 < 128)) {
          res_33556943[j_33556945] = String.fromCharCode(c_33556946);
          i_33556944 += 1;
          }
          else {
            var helper_33556959 = newSeq_33556919(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33556960 = c_33556946.toString(16);
                  if ((((code_33556960) == null ? 0 : (code_33556960).length) == 1)) {
                  helper_33556959.push("%0");;
                  }
                  else {
                  helper_33556959.push("%");;
                  }
                  
                  helper_33556959.push(code_33556960);;
                  i_33556944 += 1;
                  if ((((s_33556901).length <= i_33556944) || (s_33556901[i_33556944] < 128))) {
                  break Label3;
                  }
                  
                  c_33556946 = s_33556901[i_33556944];
                }
            };
++excHandler;
            try {
            res_33556943[j_33556945] = decodeURIComponent(helper_33556959.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            res_33556943[j_33556945] = helper_33556959.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33556945 += 1;
        }
    };
    if (res_33556943.length < j_33556945) { for (var i = res_33556943.length ; i < j_33556945 ; ++i) res_33556943.push(null); }
               else { res_33556943.length = j_33556945; };
    result_33556902 = res_33556943.join("");

  return result_33556902;

}

function raiseException(e_33556653, ename_33556654) {
    e_33556653.name = ename_33556654;
    if ((excHandler == 0)) {
    unhandledException(e_33556653);
    }
    
    throw e_33556653;

  
}

function addInt(a_33557050, b_33557051) {
        var result = a_33557050 + b_33557051;
    checkOverflowInt(result);
    return result;
  

  
}

function chckRange(i_33557324, a_33557325, b_33557326) {
  var result_33557327 = 0;

  BeforeRet: {
    if (((a_33557325 <= i_33557324) && (i_33557324 <= b_33557326))) {
    result_33557327 = i_33557324;
    break BeforeRet;
    }
    else {
    raiseRangeError();
    }
    
  };

  return result_33557327;

}

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_33557268, src_33557269, ti_33557270) {
  var result_33557279 = null;

    switch (ti_33557270.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer_33557259(ti_33557270))) {
      result_33557279 = src_33557269;
      }
      else {
        result_33557279 = [src_33557269[0], src_33557269[1]];
      }
      
      break;
    case 19:
            if (dest_33557268 === null || dest_33557268 === undefined) {
        dest_33557268 = {};
      }
      else {
        for (var key in dest_33557268) { delete dest_33557268[key]; }
      }
      for (var key in src_33557269) { dest_33557268[key] = src_33557269[key]; }
      result_33557279 = dest_33557268;
    
      break;
    case 18:
    case 17:
      if (!((ti_33557270.base == null))) {
      result_33557279 = nimCopy(dest_33557268, src_33557269, ti_33557270.base);
      }
      else {
      if ((ti_33557270.kind == 17)) {
      result_33557279 = (dest_33557268 === null || dest_33557268 === undefined) ? {m_type: ti_33557270} : dest_33557268;
      }
      else {
        result_33557279 = (dest_33557268 === null || dest_33557268 === undefined) ? {} : dest_33557268;
      }
      }
      nimCopyAux(result_33557279, src_33557269, ti_33557270.node);
      break;
    case 4:
    case 16:
            if(ArrayBuffer.isView(src_33557269)) { 
        if(dest_33557268 === null || dest_33557268 === undefined || dest_33557268.length != src_33557269.length) {
          dest_33557268 = new src_33557269.constructor(src_33557269);
        } else {
          dest_33557268.set(src_33557269, 0);
        }
        result_33557279 = dest_33557268;
      } else {
        if (src_33557269 === null) {
          result_33557279 = null;
        }
        else {
          if (dest_33557268 === null || dest_33557268 === undefined || dest_33557268.length != src_33557269.length) {
            dest_33557268 = new Array(src_33557269.length);
          }
          result_33557279 = dest_33557268;
          for (var i = 0; i < src_33557269.length; ++i) {
            result_33557279[i] = nimCopy(result_33557279[i], src_33557269[i], ti_33557270.base);
          }
        }
      }
    
      break;
    case 24:
    case 27:
            if (src_33557269 === null) {
        result_33557279 = null;
      }
      else {
        if (dest_33557268 === null || dest_33557268 === undefined || dest_33557268.length != src_33557269.length) {
          dest_33557268 = new Array(src_33557269.length);
        }
        result_33557279 = dest_33557268;
        for (var i = 0; i < src_33557269.length; ++i) {
          result_33557279[i] = nimCopy(result_33557279[i], src_33557269[i], ti_33557270.base);
        }
      }
    
      break;
    case 28:
            if (src_33557269 !== null) {
        result_33557279 = src_33557269.slice(0);
      }
    
      break;
    default: 
      result_33557279 = src_33557269;
      break;
    }

  return result_33557279;

}

function chckIndx(i_33557319, a_33557320, b_33557321) {
  var result_33557322 = 0;

  BeforeRet: {
    if (((a_33557320 <= i_33557319) && (i_33557319 <= b_33557321))) {
    result_33557322 = i_33557319;
    break BeforeRet;
    }
    else {
    raiseIndexError(i_33557319, a_33557320, b_33557321);
    }
    
  };

  return result_33557322;

}

function nimMax(a_33557108, b_33557109) {
    var Temporary1;

  var result_33557110 = 0;

  BeforeRet: {
    if ((b_33557109 <= a_33557108)) {
    Temporary1 = a_33557108;
    }
    else {
    Temporary1 = b_33557109;
    }
    
    result_33557110 = Temporary1;
    break BeforeRet;
  };

  return result_33557110;

}

function subInt(a_33557054, b_33557055) {
        var result = a_33557054 - b_33557055;
    checkOverflowInt(result);
    return result;
  

  
}

function nimMin(a_33557104, b_33557105) {
    var Temporary1;

  var result_33557106 = 0;

  BeforeRet: {
    if ((a_33557104 <= b_33557105)) {
    Temporary1 = a_33557104;
    }
    else {
    Temporary1 = b_33557105;
    }
    
    result_33557106 = Temporary1;
    break BeforeRet;
  };

  return result_33557106;

}
var ConstSet2 = setConstr([65, 90]);
var ConstSet3 = setConstr(95, 32, 46);
var ConstSet4 = setConstr(95, 32, 46);

function mulInt(a_33557058, b_33557059) {
        var result = a_33557058 * b_33557059;
    checkOverflowInt(result);
    return result;
  

  
}
var ConstSet5 = setConstr([97, 122]);
var ConstSet6 = setConstr([65, 90], [97, 122]);
var ConstSet7 = setConstr([97, 122]);
var ConstSet8 = setConstr([65, 90]);
var ConstSet9 = setConstr([65, 90], [97, 122]);

function eqStrings(a_33557041, b_33557042) {
        if (a_33557041 == b_33557042) return true;
    if (a_33557041 === null && b_33557042.length == 0) return true;
    if (b_33557042 === null && a_33557041.length == 0) return true;
    if ((!a_33557041) || (!b_33557042)) return false;
    var alen = a_33557041.length;
    if (alen != b_33557042.length) return false;
    for (var i = 0; i < alen; ++i)
      if (a_33557041[i] != b_33557042[i]) return false;
    return true;
  

  
}

function divInt(a_33557062, b_33557063) {
        if (b_33557063 == 0) raiseDivByZero();
    if (b_33557063 == -1 && a_33557062 == 2147483647) raiseOverflow();
    return Math.trunc(a_33557062 / b_33557063);
  

  
}

function makeNimstrLit(c_33556895) {
      var result = [];
  for (var i = 0; i < c_33556895.length; ++i) {
    result[i] = c_33556895.charCodeAt(i);
  }
  return result;
  

  
}

function rawEcho() {
          var buf = "";
      for (var i = 0; i < arguments.length; ++i) {
        buf += toJSStr(arguments[i]);
      }
      console.log(buf);
    

  
}

function cstrToNimstr(c_33556898) {
      var ln = c_33556898.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_33556898.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_33556898.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;
  

  
}
var ConstSet10 = setConstr(32, 10, 9, 13);
            var whiteSpace_1124073483 = nimCopy(null, ConstSet10, NTI1124073476);

function addChar(x_33557415, c_33557416) {
    x_33557415.push(c_33557416);

  
}
var ConstSet11 = setConstr(120, 88);
var objectID_1224736945 = [0];

function add_33556373(x_33556374, x_33556374_Idx, y_33556375) {
          if (x_33556374[x_33556374_Idx] === null) { x_33556374[x_33556374_Idx] = []; }
      var off = x_33556374[x_33556374_Idx].length;
      x_33556374[x_33556374_Idx].length += y_33556375.length;
      for (var i = 0; i < y_33556375.length; ++i) {
        x_33556374[x_33556374_Idx][off+i] = y_33556375.charCodeAt(i);
      }
    

  
}

function newSeq_33556919(len_33556921) {
  var result_33556922 = [];

    result_33556922 = new Array(len_33556921); for (var i = 0 ; i < len_33556921 ; ++i) { result_33556922[i] = null; }
  return result_33556922;

}

function unhandledException(e_33556649) {
    var buf_33556650 = [[]];
    if (!(((e_33556649.message).length == 0))) {
    buf_33556650[0].push.apply(buf_33556650[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110,58,32]);;
    buf_33556650[0].push.apply(buf_33556650[0], e_33556649.message);;
    }
    else {
    buf_33556650[0].push.apply(buf_33556650[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110]);;
    }
    
    buf_33556650[0].push.apply(buf_33556650[0], [32,91]);;
    add_33556373(buf_33556650, 0, e_33556649.name);
    buf_33556650[0].push.apply(buf_33556650[0], [93,10]);;
    var cbuf_33556651 = toJSStr(buf_33556650[0]);
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556651);
  }
  else {
    throw cbuf_33556651;
  }
  

  
}

function raiseOverflow() {
    raiseException({message: [111,118,101,114,45,32,111,114,32,117,110,100,101,114,102,108,111,119], parent: null, m_type: NTI134217743, name: null, trace: [], up: null}, "OverflowDefect");

  
}

function checkOverflowInt(a_33557048) {
        if (a_33557048 > 2147483647 || a_33557048 < -2147483648) raiseOverflow();
  

  
}

function raiseRangeError() {
    raiseException({message: [118,97,108,117,101,32,111,117,116,32,111,102,32,114,97,110,103,101], parent: null, m_type: NTI134217751, name: null, trace: [], up: null}, "RangeDefect");

  
}

function addChars_301990090(result_301990092, result_301990092_Idx, x_301990093, start_301990094, n_301990095) {
    var Temporary1;

    var old_301990096 = (result_301990092[result_301990092_Idx]).length;
    if (result_301990092[result_301990092_Idx].length < (Temporary1 = chckRange(addInt(old_301990096, n_301990095), 0, 2147483647), Temporary1)) { for (var i = result_301990092[result_301990092_Idx].length; i < Temporary1; ++i) result_301990092[result_301990092_Idx].push(0); }
         else {result_301990092[result_301990092_Idx].length = Temporary1; };
    Label2: {
      var iHEX60gensym4_301990110 = 0;
      var i_553648918 = 0;
      Label3: {
          Label4: while (true) {
          if (!(i_553648918 < n_301990095)) break Label4;
            iHEX60gensym4_301990110 = i_553648918;
            result_301990092[result_301990092_Idx][chckIndx(addInt(old_301990096, iHEX60gensym4_301990110), 0, (result_301990092[result_301990092_Idx]).length - 1)] = x_301990093.charCodeAt(chckIndx(addInt(start_301990094, iHEX60gensym4_301990110), 0, (x_301990093).length - 1));
            i_553648918 = addInt(i_553648918, 1);
          }
      };
    };

  
}

function addChars_301990086(result_301990088, result_301990088_Idx, x_301990089) {
    addChars_301990090(result_301990088, result_301990088_Idx, x_301990089, 0, ((x_301990089) == null ? 0 : (x_301990089).length));

  
}

function addInt_301990111(result_301990112, result_301990112_Idx, x_301990113) {
    addChars_301990086(result_301990112, result_301990112_Idx, ((x_301990113) + ""));

  
}

function addInt_301990129(result_301990130, result_301990130_Idx, x_301990131) {
    addInt_301990111(result_301990130, result_301990130_Idx, BigInt(x_301990131));

  
}

function HEX24_385875976(x_385875977) {
  var result_385875978 = [[]];

    addInt_301990129(result_385875978, 0, x_385875977);

  return result_385875978[0];

}

function isFatPointer_33557259(ti_33557260) {
  var result_33557261 = false;

  BeforeRet: {
    result_33557261 = !((ConstSet1[ti_33557260.base.kind] != undefined));
    break BeforeRet;
  };

  return result_33557261;

}

function nimCopyAux(dest_33557272, src_33557273, n_33557274) {
    switch (n_33557274.kind) {
    case 0:
      break;
    case 1:
            dest_33557272[n_33557274.offset] = nimCopy(dest_33557272[n_33557274.offset], src_33557273[n_33557274.offset], n_33557274.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_33557274.sons.length; i++) {
      nimCopyAux(dest_33557272, src_33557273, n_33557274.sons[i]);
    }
    
      break;
    case 3:
            dest_33557272[n_33557274.offset] = nimCopy(dest_33557272[n_33557274.offset], src_33557273[n_33557274.offset], n_33557274.typ);
      for (var i = 0; i < n_33557274.sons.length; ++i) {
        nimCopyAux(dest_33557272, src_33557273, n_33557274.sons[i][1]);
      }
    
      break;
    }

  
}

function raiseIndexError(i_33556812, a_33556813, b_33556814) {
    var Temporary1;

    if ((b_33556814 < a_33556813)) {
    Temporary1 = [105,110,100,101,120,32,111,117,116,32,111,102,32,98,111,117,110,100,115,44,32,116,104,101,32,99,111,110,116,97,105,110,101,114,32,105,115,32,101,109,112,116,121];
    }
    else {
    Temporary1 = ([105,110,100,101,120,32] || []).concat(HEX24_385875976(i_33556812) || [],[32,110,111,116,32,105,110,32] || [],HEX24_385875976(a_33556813) || [],[32,46,46,32] || [],HEX24_385875976(b_33556814) || []);
    }
    
    raiseException({message: nimCopy(null, Temporary1, NTI33554449), parent: null, m_type: NTI134217749, name: null, trace: [], up: null}, "IndexDefect");

  
}

function nsuFindChar(s_721421987, sub_721421988, start_721421989, last_721421990) {
    var Temporary1;

  var result_721421991 = 0;

  BeforeRet: {
    result_721421991 = (-1);
    if ((last_721421990 < 0)) {
    Temporary1 = (s_721421987).length - 1;
    }
    else {
    Temporary1 = last_721421990;
    }
    
    var last_721421992 = Temporary1;
    Label2: {
      var iHEX60gensym176_721422006 = 0;
      var colontmp__553648929 = 0;
      colontmp__553648929 = start_721421989;
      var res_553648930 = colontmp__553648929;
      Label3: {
          Label4: while (true) {
          if (!(res_553648930 <= last_721421992)) break Label4;
            iHEX60gensym176_721422006 = res_553648930;
            if ((s_721421987[chckIndx(iHEX60gensym176_721422006, 0, (s_721421987).length - 1)] == sub_721421988)) {
            result_721421991 = iHEX60gensym176_721422006;
            break BeforeRet;
            }
            
            res_553648930 = addInt(res_553648930, 1);
          }
      };
    };
  };

  return result_721421991;

}

function substr_33558084(s_33558085, first_33558086, last_33558087) {
  var result_33558088 = [];

    var first_33558089 = nimMax(first_33558086, 0);
    var L_33558090 = nimMax(addInt(subInt(nimMin(last_33558087, (s_33558085).length - 1), first_33558089), 1), 0);
    result_33558088 = nimCopy(null, mnewString(chckRange(L_33558090, 0, 2147483647)), NTI33554449);
    Label1: {
      var i_33558095 = 0;
      var colontmp__553648933 = 0;
      colontmp__553648933 = subInt(L_33558090, 1);
      var res_553648934 = 0;
      Label2: {
          Label3: while (true) {
          if (!(res_553648934 <= colontmp__553648933)) break Label3;
            i_33558095 = res_553648934;
            result_33558088[chckIndx(i_33558095, 0, (result_33558088).length - 1)] = s_33558085[chckIndx(addInt(i_33558095, first_33558089), 0, (s_33558085).length - 1)];
            res_553648934 = addInt(res_553648934, 1);
          }
      };
    };

  return result_33558088;

}

function substr_33558096(s_33558097, first_33558098) {
  var result_33558099 = [];

    result_33558099 = nimCopy(null, substr_33558084(s_33558097, first_33558098, (s_33558097).length - 1), NTI33554449);

  return result_33558099;

}

function fill_721421910(a_721421912, value_721421913) {
    var xHEX60gensym172_721421919 = 0;
    Label1: {
        Label2: while (true) {
        if (!(xHEX60gensym172_721421919 <= (a_721421912).length - 1)) break Label2;
          a_721421912[chckIndx(xHEX60gensym172_721421919, 0, (a_721421912).length - 1)] = value_721421913;
          xHEX60gensym172_721421919 = addInt(xHEX60gensym172_721421919, 1);
        }
    };

  
}

function nsuInitSkipTable(a_721421907, sub_721421908) {
    var m_721421909 = (sub_721421908).length;
    fill_721421910(a_721421907, m_721421909);
    Label1: {
      var i_721421929 = 0;
      var colontmp__553648937 = 0;
      colontmp__553648937 = subInt(m_721421909, 1);
      var i_553648938 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_553648938 < colontmp__553648937)) break Label3;
            i_721421929 = i_553648938;
            a_721421907[chckIndx(sub_721421908[chckIndx(i_721421929, 0, (sub_721421908).length - 1)], 0, (a_721421907).length - 1)] = subInt(subInt(m_721421909, 1), i_721421929);
            i_553648938 = addInt(i_553648938, 1);
          }
      };
    };

  
}

function nsuInitNewSkipTable(sub_721421962) {
  var result_721421963 = [new Int32Array(256)];

    nsuInitSkipTable(result_721421963[0], sub_721421962);

  return result_721421963[0];

}

function nsuFindStrA(a_721421965, s_721421966, sub_721421967, start_721421968, last_721421969) {
    var Temporary1;

  var result_721421970 = 0;

  BeforeRet: {
    if ((last_721421969 < 0)) {
    Temporary1 = (s_721421966).length - 1;
    }
    else {
    Temporary1 = last_721421969;
    }
    
    var last_721421971 = Temporary1;
    var subLast_721421972 = subInt((sub_721421967).length, 1);
    if ((subLast_721421972 == (-1))) {
    result_721421970 = start_721421968;
    break BeforeRet;
    }
    
    result_721421970 = (-1);
    var skip_721421973 = start_721421968;
    Label2: {
        Label3: while (true) {
        if (!(subLast_721421972 <= subInt(last_721421971, skip_721421973))) break Label3;
          var i_721421974 = subLast_721421972;
          Label4: {
              Label5: while (true) {
              if (!(s_721421966[chckIndx(addInt(skip_721421973, i_721421974), 0, (s_721421966).length - 1)] == sub_721421967[chckIndx(i_721421974, 0, (sub_721421967).length - 1)])) break Label5;
                if ((i_721421974 == 0)) {
                result_721421970 = skip_721421973;
                break BeforeRet;
                }
                
                i_721421974 = subInt(i_721421974, 1);
              }
          };
          skip_721421973 = addInt(skip_721421973, a_721421965[chckIndx(s_721421966[chckIndx(addInt(skip_721421973, subLast_721421972), 0, (s_721421966).length - 1)], 0, (a_721421965).length - 1)]);
        }
    };
  };

  return result_721421970;

}

function nsuReplaceStr(s_721422175, sub_721422176, by_721422177) {
  var result_721422178 = [];

    result_721422178 = nimCopy(null, [], NTI33554449);
    var subLen_721422179 = (sub_721422176).length;
    if ((subLen_721422179 == 0)) {
    result_721422178 = nimCopy(null, s_721422175, NTI33554449);
    }
    else {
    if ((subLen_721422179 == 1)) {
    var c_721422180 = sub_721422176[chckIndx(0, 0, (sub_721422176).length - 1)];
    var last_721422181 = (s_721422175).length - 1;
    var i_721422182 = 0;
    Label1: {
        Label2: while (true) {
        if (!true) break Label2;
          var j_721422183 = nsuFindChar(s_721422175, c_721422180, chckRange(i_721422182, 0, 2147483647), last_721422181);
          if ((j_721422183 < 0)) {
          break Label1;
          }
          
          result_721422178.push.apply(result_721422178, substr_33558084(s_721422175, i_721422182, subInt(j_721422183, 1)));;
          result_721422178.push.apply(result_721422178, by_721422177);;
          i_721422182 = addInt(j_721422183, subLen_721422179);
        }
    };
    result_721422178.push.apply(result_721422178, substr_33558096(s_721422175, i_721422182));;
    }
    else {
      var a_721422184 = nsuInitNewSkipTable(sub_721422176);
      var last_721422185 = (s_721422175).length - 1;
      var i_721422186 = 0;
      Label3: {
          Label4: while (true) {
          if (!true) break Label4;
            var j_721422187 = nsuFindStrA(a_721422184, s_721422175, sub_721422176, chckRange(i_721422186, 0, 2147483647), last_721422185);
            if ((j_721422187 < 0)) {
            break Label3;
            }
            
            result_721422178.push.apply(result_721422178, substr_33558084(s_721422175, i_721422186, subInt(j_721422187, 1)));;
            result_721422178.push.apply(result_721422178, by_721422177);;
            i_721422186 = addInt(j_721422187, subLen_721422179);
          }
      };
      result_721422178.push.apply(result_721422178, substr_33558096(s_721422175, i_721422186));;
    }
    }

  return result_721422178;

}

function nsuToLowerAsciiChar(c_721420373) {
  var result_721420374 = 0;

    if ((ConstSet2[c_721420373] != undefined)) {
    result_721420374 = (c_721420373 ^ 32);
    }
    else {
      result_721420374 = c_721420373;
    }
    

  return result_721420374;

}

function fuzzyMatch_704643088(pattern_704643089, str_704643090) {
              var Temporary4;
              var Temporary5;
                var Temporary6;
      var Temporary7;
        var Temporary8;

  var result_704643093 = {Field0: 0, Field1: false};

    var scoreState_704643094 = (-100);
    var headerMatched_704643095 = false;
    var unmatchedLeadingCharCount_704643096 = 0;
    var consecutiveMatchCount_704643097 = 0;
    var strIndex_704643098 = 0;
    var patIndex_704643099 = 0;
    var score_704643100 = 0;
    Label1: {
        Label2: while (true) {
        if (!((strIndex_704643098 < ((str_704643090) == null ? 0 : (str_704643090).length)) && (patIndex_704643099 < ((pattern_704643089) == null ? 0 : (pattern_704643089).length)))) break Label2;
          Label3: {
            var patternChar_704643103 = nsuToLowerAsciiChar(pattern_704643089.charCodeAt(chckIndx(patIndex_704643099, 0, (pattern_704643089).length - 1)));
            var strChar_704643104 = nsuToLowerAsciiChar(str_704643090.charCodeAt(chckIndx(strIndex_704643098, 0, (str_704643090).length - 1)));
            if ((ConstSet3[patternChar_704643103] != undefined)) {
            patIndex_704643099 = addInt(patIndex_704643099, 1);
            break Label3;
            }
            
            if ((ConstSet4[strChar_704643104] != undefined)) {
            strIndex_704643098 = addInt(strIndex_704643098, 1);
            break Label3;
            }
            
            if ((!(headerMatched_704643095) && (strChar_704643104 == 58))) {
            headerMatched_704643095 = true;
            scoreState_704643094 = (-100);
            score_704643100 = ((Math.floor((0.5 * score_704643100))) | 0);
            patIndex_704643099 = 0;
            strIndex_704643098 = addInt(strIndex_704643098, 1);
            break Label3;
            }
            
            if ((strChar_704643104 == patternChar_704643103)) {
            switch (scoreState_704643094) {
            case (-100):
            case 20:
              scoreState_704643094 = 10;
              break;
            case 0:
              scoreState_704643094 = 5;
              score_704643100 = addInt(score_704643100, scoreState_704643094);
              break;
            case 10:
            case 5:
              consecutiveMatchCount_704643097 = addInt(consecutiveMatchCount_704643097, 1);
              scoreState_704643094 = 5;
              score_704643100 = addInt(score_704643100, mulInt(5, consecutiveMatchCount_704643097));
              if ((scoreState_704643094 == 10)) {
              score_704643100 = addInt(score_704643100, 10);
              }
              
              var onBoundary_704643156 = (patIndex_704643099 == ((pattern_704643089) == null ? -1 : (pattern_704643089).length - 1));
              if ((!(onBoundary_704643156) && (strIndex_704643098 < ((str_704643090) == null ? -1 : (str_704643090).length - 1)))) {
              var nextPatternChar_704643157 = nsuToLowerAsciiChar(pattern_704643089.charCodeAt(chckIndx(addInt(patIndex_704643099, 1), 0, (pattern_704643089).length - 1)));
              var nextStrChar_704643158 = nsuToLowerAsciiChar(str_704643090.charCodeAt(chckIndx(addInt(strIndex_704643098, 1), 0, (str_704643090).length - 1)));
              if (!!((ConstSet5[nextStrChar_704643158] != undefined))) Temporary4 = false; else {                Temporary4 = !((nextStrChar_704643158 == nextPatternChar_704643157));              }              onBoundary_704643156 = Temporary4;
              }
              
              if (onBoundary_704643156) {
              scoreState_704643094 = 20;
              score_704643100 = addInt(score_704643100, scoreState_704643094);
              }
              
              break;
            case (-1):
            case (-3):
              if (!((ConstSet6[str_704643090.charCodeAt(chckIndx(subInt(strIndex_704643098, 1), 0, (str_704643090).length - 1))] != undefined))) Temporary5 = true; else {                if (!(ConstSet7[str_704643090.charCodeAt(chckIndx(subInt(strIndex_704643098, 1), 0, (str_704643090).length - 1))] != undefined)) Temporary6 = false; else {                  Temporary6 = (ConstSet8[str_704643090.charCodeAt(chckIndx(strIndex_704643098, 0, (str_704643090).length - 1))] != undefined);                }                Temporary5 = Temporary6;              }              var isLeadingChar_704643182 = Temporary5;
              if (isLeadingChar_704643182) {
              scoreState_704643094 = 10;
              }
              else {
                scoreState_704643094 = 0;
                score_704643100 = addInt(score_704643100, scoreState_704643094);
              }
              
              break;
            }
            patIndex_704643099 = addInt(patIndex_704643099, 1);
            }
            else {
              switch (scoreState_704643094) {
              case (-100):
                scoreState_704643094 = (-3);
                score_704643100 = addInt(score_704643100, scoreState_704643094);
                break;
              case 5:
                scoreState_704643094 = (-1);
                score_704643100 = addInt(score_704643100, scoreState_704643094);
                consecutiveMatchCount_704643097 = 0;
                break;
              case (-3):
                if ((unmatchedLeadingCharCount_704643096 < 3)) {
                scoreState_704643094 = (-3);
                score_704643100 = addInt(score_704643100, scoreState_704643094);
                }
                
                unmatchedLeadingCharCount_704643096 = addInt(unmatchedLeadingCharCount_704643096, 1);
                break;
              default: 
                scoreState_704643094 = (-1);
                score_704643100 = addInt(score_704643100, scoreState_704643094);
                break;
              }
            }
            
            strIndex_704643098 = addInt(strIndex_704643098, 1);
          };
        }
    };
      if (!(patIndex_704643099 == ((pattern_704643089) == null ? 0 : (pattern_704643089).length))) Temporary7 = false; else {        if ((strIndex_704643098 == ((str_704643090) == null ? 0 : (str_704643090).length))) Temporary8 = true; else {          Temporary8 = !((ConstSet9[str_704643090.charCodeAt(chckIndx(strIndex_704643098, 0, (str_704643090).length - 1))] != undefined));        }        Temporary7 = Temporary8;      }    if (Temporary7) {
    score_704643100 = addInt(score_704643100, 10);
    }
    
    var colontmp__553648945 = nimMax(0, score_704643100);
    var colontmp__553648946 = (0 < score_704643100);
    result_704643093 = nimCopy(result_704643093, {Field0: colontmp__553648945, Field1: colontmp__553648946}, NTI704643086);

  return result_704643093;

}

function validateUtf8_1023410512(s_1023410513) {
  var result_1023410514 = 0;

  BeforeRet: {
    var i_1023410515 = 0;
    var L_1023410519 = (s_1023410513).length;
    Label1: {
        Label2: while (true) {
        if (!(i_1023410515 < L_1023410519)) break Label2;
          if ((s_1023410513[chckIndx(i_1023410515, 0, (s_1023410513).length - 1)] <= 127)) {
          i_1023410515 = addInt(i_1023410515, 1);
          }
          else {
          if (((s_1023410513[chckIndx(i_1023410515, 0, (s_1023410513).length - 1)] >>> 5) == 6)) {
          if ((s_1023410513[chckIndx(i_1023410515, 0, (s_1023410513).length - 1)] < 194)) {
          result_1023410514 = i_1023410515;
          break BeforeRet;
          }
          
          if (((addInt(i_1023410515, 1) < L_1023410519) && ((s_1023410513[chckIndx(addInt(i_1023410515, 1), 0, (s_1023410513).length - 1)] >>> 6) == 2))) {
          i_1023410515 = addInt(i_1023410515, 2);
          }
          else {
            result_1023410514 = i_1023410515;
            break BeforeRet;
          }
          
          }
          else {
          if (((s_1023410513[chckIndx(i_1023410515, 0, (s_1023410513).length - 1)] >>> 4) == 14)) {
          if ((((addInt(i_1023410515, 2) < L_1023410519) && ((s_1023410513[chckIndx(addInt(i_1023410515, 1), 0, (s_1023410513).length - 1)] >>> 6) == 2)) && ((s_1023410513[chckIndx(addInt(i_1023410515, 2), 0, (s_1023410513).length - 1)] >>> 6) == 2))) {
          i_1023410515 = addInt(i_1023410515, 3);
          }
          else {
            result_1023410514 = i_1023410515;
            break BeforeRet;
          }
          
          }
          else {
          if (((s_1023410513[chckIndx(i_1023410515, 0, (s_1023410513).length - 1)] >>> 3) == 30)) {
          if (((((addInt(i_1023410515, 3) < L_1023410519) && ((s_1023410513[chckIndx(addInt(i_1023410515, 1), 0, (s_1023410513).length - 1)] >>> 6) == 2)) && ((s_1023410513[chckIndx(addInt(i_1023410515, 2), 0, (s_1023410513).length - 1)] >>> 6) == 2)) && ((s_1023410513[chckIndx(addInt(i_1023410515, 3), 0, (s_1023410513).length - 1)] >>> 6) == 2))) {
          i_1023410515 = addInt(i_1023410515, 4);
          }
          else {
            result_1023410514 = i_1023410515;
            break BeforeRet;
          }
          
          }
          else {
            result_1023410514 = i_1023410515;
            break BeforeRet;
          }
          }}}
        }
    };
    result_1023410514 = (-1);
    break BeforeRet;
  };

  return result_1023410514;

}

function validateUtf8_1023417537(s_1023417538) {
  var result_1023417539 = 0;

    result_1023417539 = validateUtf8_1023410512((s_1023417538.slice(0, (s_1023417538).length - 1 + 1)));

  return result_1023417539;

}

function nucruneLen(s_1023410204) {
  var result_1023410205 = 0;

    result_1023410205 = 0;
    var i_1023410206 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_1023410206 < (s_1023410204).length)) break Label2;
          if ((s_1023410204[chckIndx(i_1023410206, 0, (s_1023410204).length - 1)] <= 127)) {
          i_1023410206 = addInt(i_1023410206, 1);
          }
          else {
          if (((s_1023410204[chckIndx(i_1023410206, 0, (s_1023410204).length - 1)] >>> 5) == 6)) {
          i_1023410206 = addInt(i_1023410206, 2);
          }
          else {
          if (((s_1023410204[chckIndx(i_1023410206, 0, (s_1023410204).length - 1)] >>> 4) == 14)) {
          i_1023410206 = addInt(i_1023410206, 3);
          }
          else {
          if (((s_1023410204[chckIndx(i_1023410206, 0, (s_1023410204).length - 1)] >>> 3) == 30)) {
          i_1023410206 = addInt(i_1023410206, 4);
          }
          else {
          if (((s_1023410204[chckIndx(i_1023410206, 0, (s_1023410204).length - 1)] >>> 2) == 62)) {
          i_1023410206 = addInt(i_1023410206, 5);
          }
          else {
          if (((s_1023410204[chckIndx(i_1023410206, 0, (s_1023410204).length - 1)] >>> 1) == 126)) {
          i_1023410206 = addInt(i_1023410206, 6);
          }
          else {
          i_1023410206 = addInt(i_1023410206, 1);
          }
          }}}}}
          result_1023410205 = addInt(result_1023410205, 1);
        }
    };

  return result_1023410205;

}

function runeLen_1023417365(s_1023417366) {
  var result_1023417367 = 0;

    result_1023417367 = nucruneLen((s_1023417366.slice(0, (s_1023417366).length - 1 + 1)));

  return result_1023417367;

}

function nsuRepeatChar(c_721421409, count_721421410) {
  var result_721421411 = [];

    result_721421411 = nimCopy(null, mnewString(count_721421410), NTI33554449);
    Label1: {
      var i_721421416 = 0;
      var colontmp__553648950 = 0;
      colontmp__553648950 = subInt(count_721421410, 1);
      var res_553648951 = 0;
      Label2: {
          Label3: while (true) {
          if (!(res_553648951 <= colontmp__553648950)) break Label3;
            i_721421416 = res_553648951;
            result_721421411[chckIndx(i_721421416, 0, (result_721421411).length - 1)] = c_721421409;
            res_553648951 = addInt(res_553648951, 1);
          }
      };
    };

  return result_721421411;

}

function raiseDivByZero() {
    raiseException({message: [100,105,118,105,115,105,111,110,32,98,121,32,122,101,114,111], parent: null, m_type: NTI134217742, name: null, trace: [], up: null}, "DivByZeroDefect");

  
}

function alignString_1493172244(s_1493172245, minimumWidth_1493172246, align_1493172247, fill_1493172248) {
      var Temporary1;

  var result_1493172249 = [];

    if ((minimumWidth_1493172246 == 0)) {
    result_1493172249 = nimCopy(null, s_1493172245, NTI33554449);
    }
    else {
      if ((validateUtf8_1023417537(s_1493172245) == (-1))) {
      Temporary1 = runeLen_1023417365(s_1493172245);
      }
      else {
      Temporary1 = (s_1493172245).length;
      }
      
      var sRuneLen_1493172250 = Temporary1;
      var toFill_1493172251 = subInt(minimumWidth_1493172246, sRuneLen_1493172250);
      if ((toFill_1493172251 <= 0)) {
      result_1493172249 = nimCopy(null, s_1493172245, NTI33554449);
      }
      else {
      if (((align_1493172247 == 60) || (align_1493172247 == 0))) {
      result_1493172249 = nimCopy(null, (s_1493172245 || []).concat(nsuRepeatChar(fill_1493172248, chckRange(toFill_1493172251, 0, 2147483647)) || []), NTI33554449);
      }
      else {
      if ((align_1493172247 == 94)) {
      var half_1493172252 = divInt(toFill_1493172251, 2);
      result_1493172249 = nimCopy(null, (nsuRepeatChar(fill_1493172248, chckRange(half_1493172252, 0, 2147483647)) || []).concat(s_1493172245 || [],nsuRepeatChar(fill_1493172248, chckRange(subInt(toFill_1493172251, half_1493172252), 0, 2147483647)) || []), NTI33554449);
      }
      else {
        result_1493172249 = nimCopy(null, (nsuRepeatChar(fill_1493172248, chckRange(toFill_1493172251, 0, 2147483647)) || []).concat(s_1493172245 || []), NTI33554449);
      }
      }}
    }
    

  return result_1493172249;

}

function formatValue_553648287(result_553648289, result_553648289_Idx, value_553648290) {
    var value_553648299 = nimCopy(null, value_553648290, NTI33554449);
    result_553648289[result_553648289_Idx].push.apply(result_553648289[result_553648289_Idx], alignString_1493172244(value_553648299, 0, 0, 32));;

  
}

function formatValue_553648305(result_553648308, result_553648308_Idx, value_553648309) {
    result_553648308[result_553648308_Idx].push.apply(result_553648308[result_553648308_Idx], HEX24_385875976(value_553648309));;

  
}

function sysFatal_268435501(message_268435504) {
    raiseException({message: nimCopy(null, message_268435504, NTI33554449), m_type: NTI134217745, parent: null, name: null, trace: [], up: null}, "AssertionDefect");

  
}

function raiseAssert_268435499(msg_268435500) {
    sysFatal_268435501(msg_268435500);

  
}

function failedAssertImpl_268435541(msg_268435542) {
    raiseAssert_268435499(msg_268435542);

  
}

function onInput(e_553648154) {
    
function HEX3Aanonymous_553648333(a_553648338, b_553648339) {
      var result_553648346 = 0;

        result_553648346 = subInt(b_553648339.score, a_553648338.score);

      return result_553648346;

    }

  BeforeRet: {
    var searchContainer_553648155 = document.getElementById("search-results");
    var matches_553648156 = [];
    searchContainer_553648155.innerHTML = "";
    var input_553648157 = e_553648154.target.value;
    if ((input_553648157 == "")) {
    break BeforeRet;
    }
    
    Label1: {
      var item_553648180 = ({title: [], slug: [], contentTokens: [], displayContent: []});
      var i_553648906 = 0;
      var L_553648907 = (searchDB_553648145[0]).length;
      Label2: {
          Label3: while (true) {
          if (!(i_553648906 < L_553648907)) break Label3;
            item_553648180 = searchDB_553648145[0][chckIndx(i_553648906, 0, (searchDB_553648145[0]).length - 1)];
            var title_553648181 = nsuReplaceStr(item_553648180.slug, [46,104,116,109,108], []);
            Label4: {
              var token_553648203 = [];
              var i_553648902 = 0;
              var L_553648903 = (item_553648180.contentTokens).length;
              Label5: {
                  Label6: while (true) {
                  if (!(i_553648902 < L_553648903)) break Label6;
                    token_553648203 = item_553648180.contentTokens[chckIndx(i_553648902, 0, (item_553648180.contentTokens).length - 1)];
                    var tmpTuple_553648204 = fuzzyMatch_704643088(input_553648157, toJSStr(token_553648203));
                    var score_553648205 = tmpTuple_553648204["Field0"];
                    var match_553648206 = tmpTuple_553648204["Field1"];
                    if (match_553648206) {
                    var exists_553648207 = false;
                    Label7: {
                      var i_553648271 = 0;
                      var m_553648272 = ({element: [], slug: [], count: 0, score: 0});
                      var i_553648897 = 0;
                      var L_553648898 = (matches_553648156).length;
                      Label8: {
                          Label9: while (true) {
                          if (!(i_553648897 < L_553648898)) break Label9;
                            i_553648271 = i_553648897;
                            m_553648272 = nimCopy(m_553648272, matches_553648156[chckIndx(i_553648897, 0, (matches_553648156).length - 1)], NTI553648131);
                            if (eqStrings(m_553648272.slug, item_553648180.slug)) {
                            exists_553648207 = true;
                            matches_553648156[chckIndx(i_553648271, 0, (matches_553648156).length - 1)].count = addInt(m_553648272.count, 1);
                            Label10: {
                              var fmtRes_553648281 = [mnewString(0)];
                              fmtRes_553648281[0].push.apply(fmtRes_553648281[0], [60,97,32,104,114,101,102,61,39]);;
                              formatValue_553648287(fmtRes_553648281, 0, item_553648180.slug);
                              fmtRes_553648281[0].push.apply(fmtRes_553648281[0], [39,62]);;
                              formatValue_553648287(fmtRes_553648281, 0, title_553648181);
                              fmtRes_553648281[0].push.apply(fmtRes_553648281[0], [40]);;
                              formatValue_553648305(fmtRes_553648281, 0, matches_553648156[chckIndx(i_553648271, 0, (matches_553648156).length - 1)].count);
                              fmtRes_553648281[0].push.apply(fmtRes_553648281[0], [32,109,97,116,99,104,101,115,41,60,47,97,62]);;
                            };
                            var webNode_553648311 = nimCopy(null, fmtRes_553648281[0], NTI33554449);
                            matches_553648156[chckIndx(i_553648271, 0, (matches_553648156).length - 1)].element = nimCopy(null, webNode_553648311, NTI33554449);
                            }
                            
                            i_553648897 += 1;
                            if (!(((matches_553648156).length == L_553648898))) {
                            failedAssertImpl_268435541(makeNimstrLit("iterators.nim(187, 11) `len(a) == L` the length of the seq changed while iterating over it"));
                            }
                            
                          }
                      };
                    };
                    if (!(exists_553648207)) {
                    Label11: {
                      var fmtRes_553648316 = [mnewString(0)];
                      fmtRes_553648316[0].push.apply(fmtRes_553648316[0], [60,97,32,104,114,101,102,61,39]);;
                      formatValue_553648287(fmtRes_553648316, 0, item_553648180.slug);
                      fmtRes_553648316[0].push.apply(fmtRes_553648316[0], [39,62]);;
                      formatValue_553648287(fmtRes_553648316, 0, title_553648181);
                      fmtRes_553648316[0].push.apply(fmtRes_553648316[0], [40,49,32,109,97,116,99,104,41,60,47,97,62]);;
                    };
                    var webNode_553648327 = nimCopy(null, fmtRes_553648316[0], NTI33554449);
                    var sResult_553648328 = ({element: [], slug: [], count: 0, score: 0});
                    sResult_553648328.slug = nimCopy(null, item_553648180.slug, NTI33554449);
                    sResult_553648328.element = nimCopy(null, webNode_553648327, NTI33554449);
                    sResult_553648328.score = score_553648205;
                    sResult_553648328.count = 0;
                    var Temporary12 = nimCopy(null, sResult_553648328, NTI553648131);
                    matches_553648156.push(Temporary12);;
                    }
                    
                    }
                    
                    i_553648902 += 1;
                    if (!(((item_553648180.contentTokens).length == L_553648903))) {
                    failedAssertImpl_268435541(makeNimstrLit("iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
                    }
                    
                  }
              };
            };
            i_553648906 += 1;
            if (!(((searchDB_553648145[0]).length == L_553648907))) {
            failedAssertImpl_268435541(makeNimstrLit("iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    matches_553648156.sort(HEX3Aanonymous_553648333);
    Label13: {
      var m_553648376 = ({element: [], slug: [], count: 0, score: 0});
      var i_553648911 = 0;
      var L_553648912 = (matches_553648156).length;
      Label14: {
          Label15: while (true) {
          if (!(i_553648911 < L_553648912)) break Label15;
            m_553648376 = matches_553648156[chckIndx(i_553648911, 0, (matches_553648156).length - 1)];
            var container_553648377 = document.createElement("div");
            container_553648377.classList.add("mudkip-search-item");
            container_553648377.innerHTML = toJSStr(m_553648376.element);
            searchContainer_553648155.appendChild(container_553648377);
            i_553648911 += 1;
            if (!(((matches_553648156).length == L_553648912))) {
            failedAssertImpl_268435541(makeNimstrLit("iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
  };

  
}

function parseHex_721421283(s_721421285, number_721421286, number_721421286_Idx, maxLen_721421287) {
    var Temporary1;

  var result_721421288 = 0;

    var i_721421289 = 0;
    var output_721421290 = 0;
    var foundDigit_721421291 = false;
    if ((maxLen_721421287 == 0)) {
    Temporary1 = (s_721421285).length;
    }
    else {
    Temporary1 = addInt(i_721421289, maxLen_721421287);
    }
    
    var last_721421298 = nimMin((s_721421285).length, Temporary1);
    if ((((addInt(i_721421289, 1) < last_721421298) && (s_721421285[chckIndx(i_721421289, 0, (s_721421285).length - 1)] == 48)) && (ConstSet11[s_721421285[chckIndx(addInt(i_721421289, 1), 0, (s_721421285).length - 1)]] != undefined))) {
    i_721421289 = addInt(i_721421289, 2);
    }
    else {
    if (((i_721421289 < last_721421298) && (s_721421285[chckIndx(i_721421289, 0, (s_721421285).length - 1)] == 35))) {
    i_721421289 = addInt(i_721421289, 1);
    }
    }
    Label2: {
        Label3: while (true) {
        if (!(i_721421289 < last_721421298)) break Label3;
          switch (s_721421285[chckIndx(i_721421289, 0, (s_721421285).length - 1)]) {
          case 95:
            break;
          case 48:
          case 49:
          case 50:
          case 51:
          case 52:
          case 53:
          case 54:
          case 55:
          case 56:
          case 57:
            output_721421290 = (((output_721421290 << 4) << 0 >> 0) | subInt(s_721421285[chckIndx(i_721421289, 0, (s_721421285).length - 1)], 48));
            foundDigit_721421291 = true;
            break;
          case 97:
          case 98:
          case 99:
          case 100:
          case 101:
          case 102:
            output_721421290 = (((output_721421290 << 4) << 0 >> 0) | addInt(subInt(s_721421285[chckIndx(i_721421289, 0, (s_721421285).length - 1)], 97), 10));
            foundDigit_721421291 = true;
            break;
          case 65:
          case 66:
          case 67:
          case 68:
          case 69:
          case 70:
            output_721421290 = (((output_721421290 << 4) << 0 >> 0) | addInt(subInt(s_721421285[chckIndx(i_721421289, 0, (s_721421285).length - 1)], 65), 10));
            foundDigit_721421291 = true;
            break;
          default: 
            break Label2;
            break;
          }
          i_721421289 = addInt(i_721421289, 1);
        }
    };
    if (foundDigit_721421291) {
    number_721421286[number_721421286_Idx] = output_721421290;
    result_721421288 = i_721421289;
    }
    

  return result_721421288;

}

function parseHex_721421276(s_721421278, number_721421279, number_721421279_Idx, start_721421280, maxLen_721421281) {
  var result_721421282 = 0;

    result_721421282 = parseHex_721421283((s_721421278.slice(start_721421280, (s_721421278).length - 1 + 1)), number_721421279, number_721421279_Idx, maxLen_721421281);

  return result_721421282;

}

function nsuParseHexInt(s_721421274) {
  var result_721421275 = [0];

    result_721421275[0] = 0;
    var L_721421348 = parseHex_721421276(s_721421274, result_721421275, 0, 0, 0);
    if ((!((L_721421348 == (s_721421274).length)) || (L_721421348 == 0))) {
    raiseException({message: ([105,110,118,97,108,105,100,32,104,101,120,32,105,110,116,101,103,101,114,58,32] || []).concat(s_721421274 || []), parent: null, m_type: NTI134217746, name: null, trace: [], up: null}, "ValueError");
    }
    

  return result_721421275[0];

}

function HEX5BHEX5D_721421567(s_721421570, x_721421571) {
  var result_721421572 = [];

    var a_721421574 = x_721421571.a;
    var L_721421576 = addInt(subInt(x_721421571.b, a_721421574), 1);
    result_721421572 = nimCopy(null, mnewString(chckRange(L_721421576, 0, 2147483647)), NTI33554449);
    Label1: {
      var i_721421581 = 0;
      var i_553648972 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_553648972 < L_721421576)) break Label3;
            i_721421581 = i_553648972;
            result_721421572[chckIndx(i_721421581, 0, (result_721421572).length - 1)] = s_721421570[chckIndx(addInt(i_721421581, a_721421574), 0, (s_721421570).length - 1)];
            i_553648972 = addInt(i_553648972, 1);
          }
      };
    };

  return result_721421572;

}

function HEX2EHEX2E_1040187440(a_1040187443, b_1040187444) {
  var result_1040187445 = ({a: 0, b: 0});

    result_1040187445 = nimCopy(result_1040187445, {a: a_1040187443, b: b_1040187444}, NTI771752005);

  return result_1040187445;

}

function HEX3CHEX3DHEX25_33555507(x_33555508, y_33555509) {
  var result_33555510 = false;

    result_33555510 = (Number(BigInt.asUintN(32, BigInt(x_33555508))) <= Number(BigInt.asUintN(32, BigInt(y_33555509))));

  return result_33555510;

}

function nuctoUTF8(c_1023410583) {
  var result_1023410584 = [];

    result_1023410584 = nimCopy(null, [], NTI33554449);
    var iHEX60gensym21_1023410586 = c_1023410583;
    if (HEX3CHEX3DHEX25_33555507(iHEX60gensym21_1023410586, 127)) {
    if (result_1023410584.length < 1) { for (var i = result_1023410584.length; i < 1; ++i) result_1023410584.push(0); }
         else {result_1023410584.length = 1; };
    result_1023410584[chckIndx(0, 0, (result_1023410584).length - 1)] = chckRange(iHEX60gensym21_1023410586, 0, 255);
    }
    else {
    if (HEX3CHEX3DHEX25_33555507(iHEX60gensym21_1023410586, 2047)) {
    if (result_1023410584.length < 2) { for (var i = result_1023410584.length; i < 2; ++i) result_1023410584.push(0); }
         else {result_1023410584.length = 2; };
    result_1023410584[chckIndx(0, 0, (result_1023410584).length - 1)] = chckRange(((iHEX60gensym21_1023410586 >> 6) | 192), 0, 255);
    result_1023410584[chckIndx(1, 0, (result_1023410584).length - 1)] = chckRange(((iHEX60gensym21_1023410586 & 63) | 128), 0, 255);
    }
    else {
    if (HEX3CHEX3DHEX25_33555507(iHEX60gensym21_1023410586, 65535)) {
    if (result_1023410584.length < 3) { for (var i = result_1023410584.length; i < 3; ++i) result_1023410584.push(0); }
         else {result_1023410584.length = 3; };
    result_1023410584[chckIndx(0, 0, (result_1023410584).length - 1)] = chckRange(((iHEX60gensym21_1023410586 >> 12) | 224), 0, 255);
    result_1023410584[chckIndx(1, 0, (result_1023410584).length - 1)] = chckRange((((iHEX60gensym21_1023410586 >> 6) & 63) | 128), 0, 255);
    result_1023410584[chckIndx(2, 0, (result_1023410584).length - 1)] = chckRange(((iHEX60gensym21_1023410586 & 63) | 128), 0, 255);
    }
    else {
    if (HEX3CHEX3DHEX25_33555507(iHEX60gensym21_1023410586, 2097151)) {
    if (result_1023410584.length < 4) { for (var i = result_1023410584.length; i < 4; ++i) result_1023410584.push(0); }
         else {result_1023410584.length = 4; };
    result_1023410584[chckIndx(0, 0, (result_1023410584).length - 1)] = chckRange(((iHEX60gensym21_1023410586 >> 18) | 240), 0, 255);
    result_1023410584[chckIndx(1, 0, (result_1023410584).length - 1)] = chckRange((((iHEX60gensym21_1023410586 >> 12) & 63) | 128), 0, 255);
    result_1023410584[chckIndx(2, 0, (result_1023410584).length - 1)] = chckRange((((iHEX60gensym21_1023410586 >> 6) & 63) | 128), 0, 255);
    result_1023410584[chckIndx(3, 0, (result_1023410584).length - 1)] = chckRange(((iHEX60gensym21_1023410586 & 63) | 128), 0, 255);
    }
    else {
    if (HEX3CHEX3DHEX25_33555507(iHEX60gensym21_1023410586, 67108863)) {
    if (result_1023410584.length < 5) { for (var i = result_1023410584.length; i < 5; ++i) result_1023410584.push(0); }
         else {result_1023410584.length = 5; };
    result_1023410584[chckIndx(0, 0, (result_1023410584).length - 1)] = chckRange(((iHEX60gensym21_1023410586 >> 24) | 248), 0, 255);
    result_1023410584[chckIndx(1, 0, (result_1023410584).length - 1)] = chckRange((((iHEX60gensym21_1023410586 >> 18) & 63) | 128), 0, 255);
    result_1023410584[chckIndx(2, 0, (result_1023410584).length - 1)] = chckRange((((iHEX60gensym21_1023410586 >> 12) & 63) | 128), 0, 255);
    result_1023410584[chckIndx(3, 0, (result_1023410584).length - 1)] = chckRange((((iHEX60gensym21_1023410586 >> 6) & 63) | 128), 0, 255);
    result_1023410584[chckIndx(4, 0, (result_1023410584).length - 1)] = chckRange(((iHEX60gensym21_1023410586 & 63) | 128), 0, 255);
    }
    else {
    if (HEX3CHEX3DHEX25_33555507(iHEX60gensym21_1023410586, 2147483647)) {
    if (result_1023410584.length < 6) { for (var i = result_1023410584.length; i < 6; ++i) result_1023410584.push(0); }
         else {result_1023410584.length = 6; };
    result_1023410584[chckIndx(0, 0, (result_1023410584).length - 1)] = chckRange(((iHEX60gensym21_1023410586 >> 30) | 252), 0, 255);
    result_1023410584[chckIndx(1, 0, (result_1023410584).length - 1)] = chckRange((((iHEX60gensym21_1023410586 >> 24) & 63) | 128), 0, 255);
    result_1023410584[chckIndx(2, 0, (result_1023410584).length - 1)] = chckRange((((iHEX60gensym21_1023410586 >> 18) & 63) | 128), 0, 255);
    result_1023410584[chckIndx(3, 0, (result_1023410584).length - 1)] = chckRange((((iHEX60gensym21_1023410586 >> 12) & 63) | 128), 0, 255);
    result_1023410584[chckIndx(4, 0, (result_1023410584).length - 1)] = chckRange((((iHEX60gensym21_1023410586 >> 6) & 63) | 128), 0, 255);
    result_1023410584[chckIndx(5, 0, (result_1023410584).length - 1)] = chckRange(((iHEX60gensym21_1023410586 & 63) | 128), 0, 255);
    }
    else {
    }
    }}}}}

  return result_1023410584;

}

function parseStringSlow_1124073679(s_1124073680, i_1124073681, i_1124073681_Idx, v_1124073682, v_1124073682_Idx) {
    Label1: {
        Label2: while (true) {
        if (!(i_1124073681[i_1124073681_Idx] < (s_1124073680).length)) break Label2;
          var c_1124073683 = s_1124073680[i_1124073681[i_1124073681_Idx]];
          switch (c_1124073683) {
          case 34:
            break Label1;
            break;
          case 92:
            i_1124073681[i_1124073681_Idx] += 1;
            var c_1124073689 = s_1124073680[i_1124073681[i_1124073681_Idx]];
            switch (c_1124073689) {
            case 34:
            case 92:
            case 47:
              addChar(v_1124073682[v_1124073682_Idx], c_1124073689);;
              break;
            case 98:
              addChar(v_1124073682[v_1124073682_Idx], 8);;
              break;
            case 102:
              addChar(v_1124073682[v_1124073682_Idx], 12);;
              break;
            case 110:
              addChar(v_1124073682[v_1124073682_Idx], 10);;
              break;
            case 114:
              addChar(v_1124073682[v_1124073682_Idx], 13);;
              break;
            case 116:
              addChar(v_1124073682[v_1124073682_Idx], 9);;
              break;
            case 117:
              i_1124073681[i_1124073681_Idx] += 1;
              var u_1124073719 = nsuParseHexInt(HEX5BHEX5D_721421567(s_1124073680, HEX2EHEX2E_1040187440(i_1124073681[i_1124073681_Idx], ((i_1124073681[i_1124073681_Idx] + 4) - 1))));
              i_1124073681[i_1124073681_Idx] += 3;
              v_1124073682[v_1124073682_Idx].push.apply(v_1124073682[v_1124073682_Idx], nuctoUTF8(((u_1124073719) | 0)));;
              break;
            default: 
              addChar(v_1124073682[v_1124073682_Idx], c_1124073689);;
              break;
            }
            break;
          default: 
            addChar(v_1124073682[v_1124073682_Idx], c_1124073683);;
            break;
          }
          i_1124073681[i_1124073681_Idx] += 1;
        }
    };
    Label3: {
        Label4: while (true) {
        if (!(i_1124073681[i_1124073681_Idx] < (s_1124073680).length)) break Label4;
          var cHEX60gensym14_1124073730 = s_1124073680[i_1124073681[i_1124073681_Idx]];
          if (!((whiteSpace_1124073483[cHEX60gensym14_1124073730] != undefined))) {
          break Label3;
          }
          
          i_1124073681[i_1124073681_Idx] += 1;
        }
    };
    if (((s_1124073680).length <= i_1124073681[i_1124073681_Idx])) {
    raiseException({message: ([69,120,112,101,99,116,101,100,32,34,32,98,117,116,32,101,110,100,32,114,101,97,99,104,101,100,46,32,65,116,32,111,102,102,115,101,116,58,32] || []).concat(HEX24_385875976(i_1124073681[i_1124073681_Idx]) || []), parent: null, m_type: NTI1124073475, name: null, trace: [], up: null}, "JsonError");
    }
    
    if ((s_1124073680[i_1124073681[i_1124073681_Idx]] == 34)) {
    i_1124073681[i_1124073681_Idx] += 1;
    }
    else {
      raiseException({message: ([69,120,112,101,99,116,101,100,32,34,32,98,117,116,32,103,111,116,32] || []).concat([s_1124073680[i_1124073681[i_1124073681_Idx]]],[32,105,110,115,116,101,97,100,46,32,65,116,32,111,102,102,115,101,116,58,32] || [],HEX24_385875976(i_1124073681[i_1124073681_Idx]) || []), parent: null, m_type: NTI1124073475, name: null, trace: [], up: null}, "JsonError");
    }
    

  
}

function parseHook_1124073944(s_1124073945, i_1124073946, i_1124073946_Idx, v_1124073947, v_1124073947_Idx) {
  BeforeRet: {
    Label1: {
        Label2: while (true) {
        if (!(i_1124073946[i_1124073946_Idx] < (s_1124073945).length)) break Label2;
          var cHEX60gensym47_1124073949 = s_1124073945[i_1124073946[i_1124073946_Idx]];
          if (!((whiteSpace_1124073483[cHEX60gensym47_1124073949] != undefined))) {
          break Label1;
          }
          
          i_1124073946[i_1124073946_Idx] += 1;
        }
    };
    if (((((((i_1124073946[i_1124073946_Idx] + 3) < (s_1124073945).length) && (s_1124073945[(i_1124073946[i_1124073946_Idx] + 0)] == 110)) && (s_1124073945[(i_1124073946[i_1124073946_Idx] + 1)] == 117)) && (s_1124073945[(i_1124073946[i_1124073946_Idx] + 2)] == 108)) && (s_1124073945[(i_1124073946[i_1124073946_Idx] + 3)] == 108))) {
    i_1124073946[i_1124073946_Idx] += 4;
    break BeforeRet;
    }
    
    Label3: {
        Label4: while (true) {
        if (!(i_1124073946[i_1124073946_Idx] < (s_1124073945).length)) break Label4;
          var cHEX60gensym51_1124073964 = s_1124073945[i_1124073946[i_1124073946_Idx]];
          if (!((whiteSpace_1124073483[cHEX60gensym51_1124073964] != undefined))) {
          break Label3;
          }
          
          i_1124073946[i_1124073946_Idx] += 1;
        }
    };
    if (((s_1124073945).length <= i_1124073946[i_1124073946_Idx])) {
    raiseException({message: ([69,120,112,101,99,116,101,100,32,34,32,98,117,116,32,101,110,100,32,114,101,97,99,104,101,100,46,32,65,116,32,111,102,102,115,101,116,58,32] || []).concat(HEX24_385875976(i_1124073946[i_1124073946_Idx]) || []), parent: null, m_type: NTI1124073475, name: null, trace: [], up: null}, "JsonError");
    }
    
    if ((s_1124073945[i_1124073946[i_1124073946_Idx]] == 34)) {
    i_1124073946[i_1124073946_Idx] += 1;
    }
    else {
      raiseException({message: ([69,120,112,101,99,116,101,100,32,34,32,98,117,116,32,103,111,116,32] || []).concat([s_1124073945[i_1124073946[i_1124073946_Idx]]],[32,105,110,115,116,101,97,100,46,32,65,116,32,111,102,102,115,101,116,58,32] || [],HEX24_385875976(i_1124073946[i_1124073946_Idx]) || []), parent: null, m_type: NTI1124073475, name: null, trace: [], up: null}, "JsonError");
    }
    
    parseStringSlow_1124073679(s_1124073945, i_1124073946, i_1124073946_Idx, v_1124073947, v_1124073947_Idx);
  };

  
}

function parseHook_553648676(s_553648678, i_553648679, i_553648679_Idx, v_553648680, v_553648680_Idx) {
    Label1: {
        Label2: while (true) {
        if (!(i_553648679[i_553648679_Idx] < (s_553648678).length)) break Label2;
          var cHEX60gensym62_553648682 = s_553648678[i_553648679[i_553648679_Idx]];
          if (!((whiteSpace_1124073483[cHEX60gensym62_553648682] != undefined))) {
          break Label1;
          }
          
          i_553648679[i_553648679_Idx] += 1;
        }
    };
    if (((s_553648678).length <= i_553648679[i_553648679_Idx])) {
    raiseException({message: ([69,120,112,101,99,116,101,100,32,91,32,98,117,116,32,101,110,100,32,114,101,97,99,104,101,100,46,32,65,116,32,111,102,102,115,101,116,58,32] || []).concat(HEX24_385875976(i_553648679[i_553648679_Idx]) || []), parent: null, m_type: NTI1124073475, name: null, trace: [], up: null}, "JsonError");
    }
    
    if ((s_553648678[i_553648679[i_553648679_Idx]] == 91)) {
    i_553648679[i_553648679_Idx] += 1;
    }
    else {
      raiseException({message: ([69,120,112,101,99,116,101,100,32,91,32,98,117,116,32,103,111,116,32] || []).concat([s_553648678[i_553648679[i_553648679_Idx]]],[32,105,110,115,116,101,97,100,46,32,65,116,32,111,102,102,115,101,116,58,32] || [],HEX24_385875976(i_553648679[i_553648679_Idx]) || []), parent: null, m_type: NTI1124073475, name: null, trace: [], up: null}, "JsonError");
    }
    
    Label3: {
        Label4: while (true) {
        if (!(i_553648679[i_553648679_Idx] < (s_553648678).length)) break Label4;
          Label5: {
              Label6: while (true) {
              if (!(i_553648679[i_553648679_Idx] < (s_553648678).length)) break Label6;
                var cHEX60gensym72_553648700 = s_553648678[i_553648679[i_553648679_Idx]];
                if (!((whiteSpace_1124073483[cHEX60gensym72_553648700] != undefined))) {
                break Label5;
                }
                
                i_553648679[i_553648679_Idx] += 1;
              }
          };
          if (((i_553648679[i_553648679_Idx] < (s_553648678).length) && (s_553648678[i_553648679[i_553648679_Idx]] == 93))) {
          break Label3;
          }
          
          var element_553648710 = [[]];
          parseHook_1124073944(s_553648678, i_553648679, i_553648679_Idx, element_553648710, 0);
          var Temporary7 = nimCopy(null, element_553648710[0], NTI33554449);
          v_553648680[v_553648680_Idx].push(Temporary7);;
          Label8: {
              Label9: while (true) {
              if (!(i_553648679[i_553648679_Idx] < (s_553648678).length)) break Label9;
                var cHEX60gensym76_553648716 = s_553648678[i_553648679[i_553648679_Idx]];
                if (!((whiteSpace_1124073483[cHEX60gensym76_553648716] != undefined))) {
                break Label8;
                }
                
                i_553648679[i_553648679_Idx] += 1;
              }
          };
          if (((i_553648679[i_553648679_Idx] < (s_553648678).length) && (s_553648678[i_553648679[i_553648679_Idx]] == 44))) {
          i_553648679[i_553648679_Idx] += 1;
          }
          else {
            break Label3;
          }
          
        }
    };
    Label10: {
        Label11: while (true) {
        if (!(i_553648679[i_553648679_Idx] < (s_553648678).length)) break Label11;
          var cHEX60gensym81_553648732 = s_553648678[i_553648679[i_553648679_Idx]];
          if (!((whiteSpace_1124073483[cHEX60gensym81_553648732] != undefined))) {
          break Label10;
          }
          
          i_553648679[i_553648679_Idx] += 1;
        }
    };
    if (((s_553648678).length <= i_553648679[i_553648679_Idx])) {
    raiseException({message: ([69,120,112,101,99,116,101,100,32,93,32,98,117,116,32,101,110,100,32,114,101,97,99,104,101,100,46,32,65,116,32,111,102,102,115,101,116,58,32] || []).concat(HEX24_385875976(i_553648679[i_553648679_Idx]) || []), parent: null, m_type: NTI1124073475, name: null, trace: [], up: null}, "JsonError");
    }
    
    if ((s_553648678[i_553648679[i_553648679_Idx]] == 93)) {
    i_553648679[i_553648679_Idx] += 1;
    }
    else {
      raiseException({message: ([69,120,112,101,99,116,101,100,32,93,32,98,117,116,32,103,111,116,32] || []).concat([s_553648678[i_553648679[i_553648679_Idx]]],[32,105,110,115,116,101,97,100,46,32,65,116,32,111,102,102,115,101,116,58,32] || [],HEX24_385875976(i_553648679[i_553648679_Idx]) || []), parent: null, m_type: NTI1124073475, name: null, trace: [], up: null}, "JsonError");
    }
    

  
}

function parseSymbol_1124073552(s_1124073553, i_1124073554, i_1124073554_Idx) {
  var result_1124073555 = [];

  BeforeRet: {
    Label1: {
        Label2: while (true) {
        if (!(i_1124073554[i_1124073554_Idx] < (s_1124073553).length)) break Label2;
          var cHEX60gensym0_1124073557 = s_1124073553[i_1124073554[i_1124073554_Idx]];
          if (!((whiteSpace_1124073483[cHEX60gensym0_1124073557] != undefined))) {
          break Label1;
          }
          
          i_1124073554[i_1124073554_Idx] += 1;
        }
    };
    var j_1124073567 = i_1124073554[i_1124073554_Idx];
    Label3: {
        Label4: while (true) {
        if (!(i_1124073554[i_1124073554_Idx] < (s_1124073553).length)) break Label4;
          switch (s_1124073553[i_1124073554[i_1124073554_Idx]]) {
          case 44:
          case 125:
          case 93:
          case 9:
          case 10:
          case 13:
          case 32:
            break Label3;
            break;
          default: 
            break;
          }
          i_1124073554[i_1124073554_Idx] += 1;
        }
    };
    result_1124073555 = nimCopy(null, HEX5BHEX5D_721421567(s_1124073553, HEX2EHEX2E_1040187440(j_1124073567, (i_1124073554[i_1124073554_Idx] - 1))), NTI33554449);
    break BeforeRet;
  };

  return result_1124073555;

}

function skipValue_1124074004(s_1124074005, i_1124074006, i_1124074006_Idx) {
    Label1: {
        Label2: while (true) {
        if (!(i_1124074006[i_1124074006_Idx] < (s_1124074005).length)) break Label2;
          var cHEX60gensym64_1124074008 = s_1124074005[i_1124074006[i_1124074006_Idx]];
          if (!((whiteSpace_1124073483[cHEX60gensym64_1124074008] != undefined))) {
          break Label1;
          }
          
          i_1124074006[i_1124074006_Idx] += 1;
        }
    };
    if (((i_1124074006[i_1124074006_Idx] < (s_1124074005).length) && (s_1124074005[i_1124074006[i_1124074006_Idx]] == 123))) {
    Label3: {
        Label4: while (true) {
        if (!(i_1124074006[i_1124074006_Idx] < (s_1124074005).length)) break Label4;
          var cHEX60gensym68_1124074019 = s_1124074005[i_1124074006[i_1124074006_Idx]];
          if (!((whiteSpace_1124073483[cHEX60gensym68_1124074019] != undefined))) {
          break Label3;
          }
          
          i_1124074006[i_1124074006_Idx] += 1;
        }
    };
    if (((s_1124074005).length <= i_1124074006[i_1124074006_Idx])) {
    raiseException({message: ([69,120,112,101,99,116,101,100,32,123,32,98,117,116,32,101,110,100,32,114,101,97,99,104,101,100,46,32,65,116,32,111,102,102,115,101,116,58,32] || []).concat(HEX24_385875976(i_1124074006[i_1124074006_Idx]) || []), parent: null, m_type: NTI1124073475, name: null, trace: [], up: null}, "JsonError");
    }
    
    if ((s_1124074005[i_1124074006[i_1124074006_Idx]] == 123)) {
    i_1124074006[i_1124074006_Idx] += 1;
    }
    else {
      raiseException({message: ([69,120,112,101,99,116,101,100,32,123,32,98,117,116,32,103,111,116,32] || []).concat([s_1124074005[i_1124074006[i_1124074006_Idx]]],[32,105,110,115,116,101,97,100,46,32,65,116,32,111,102,102,115,101,116,58,32] || [],HEX24_385875976(i_1124074006[i_1124074006_Idx]) || []), parent: null, m_type: NTI1124073475, name: null, trace: [], up: null}, "JsonError");
    }
    
    Label5: {
        Label6: while (true) {
        if (!(i_1124074006[i_1124074006_Idx] < (s_1124074005).length)) break Label6;
          Label7: {
              Label8: while (true) {
              if (!(i_1124074006[i_1124074006_Idx] < (s_1124074005).length)) break Label8;
                var cHEX60gensym78_1124074037 = s_1124074005[i_1124074006[i_1124074006_Idx]];
                if (!((whiteSpace_1124073483[cHEX60gensym78_1124074037] != undefined))) {
                break Label7;
                }
                
                i_1124074006[i_1124074006_Idx] += 1;
              }
          };
          if (((i_1124074006[i_1124074006_Idx] < (s_1124074005).length) && (s_1124074005[i_1124074006[i_1124074006_Idx]] == 125))) {
          break Label5;
          }
          
          skipValue_1124074004(s_1124074005, i_1124074006, i_1124074006_Idx);
          Label9: {
              Label10: while (true) {
              if (!(i_1124074006[i_1124074006_Idx] < (s_1124074005).length)) break Label10;
                var cHEX60gensym82_1124074048 = s_1124074005[i_1124074006[i_1124074006_Idx]];
                if (!((whiteSpace_1124073483[cHEX60gensym82_1124074048] != undefined))) {
                break Label9;
                }
                
                i_1124074006[i_1124074006_Idx] += 1;
              }
          };
          if (((s_1124074005).length <= i_1124074006[i_1124074006_Idx])) {
          raiseException({message: ([69,120,112,101,99,116,101,100,32,58,32,98,117,116,32,101,110,100,32,114,101,97,99,104,101,100,46,32,65,116,32,111,102,102,115,101,116,58,32] || []).concat(HEX24_385875976(i_1124074006[i_1124074006_Idx]) || []), parent: null, m_type: NTI1124073475, name: null, trace: [], up: null}, "JsonError");
          }
          
          if ((s_1124074005[i_1124074006[i_1124074006_Idx]] == 58)) {
          i_1124074006[i_1124074006_Idx] += 1;
          }
          else {
            raiseException({message: ([69,120,112,101,99,116,101,100,32,58,32,98,117,116,32,103,111,116,32] || []).concat([s_1124074005[i_1124074006[i_1124074006_Idx]]],[32,105,110,115,116,101,97,100,46,32,65,116,32,111,102,102,115,101,116,58,32] || [],HEX24_385875976(i_1124074006[i_1124074006_Idx]) || []), parent: null, m_type: NTI1124073475, name: null, trace: [], up: null}, "JsonError");
          }
          
          skipValue_1124074004(s_1124074005, i_1124074006, i_1124074006_Idx);
          Label11: {
              Label12: while (true) {
              if (!(i_1124074006[i_1124074006_Idx] < (s_1124074005).length)) break Label12;
                var cHEX60gensym92_1124074066 = s_1124074005[i_1124074006[i_1124074006_Idx]];
                if (!((whiteSpace_1124073483[cHEX60gensym92_1124074066] != undefined))) {
                break Label11;
                }
                
                i_1124074006[i_1124074006_Idx] += 1;
              }
          };
          if (((i_1124074006[i_1124074006_Idx] < (s_1124074005).length) && (s_1124074005[i_1124074006[i_1124074006_Idx]] == 44))) {
          i_1124074006[i_1124074006_Idx] += 1;
          }
          
        }
    };
    Label13: {
        Label14: while (true) {
        if (!(i_1124074006[i_1124074006_Idx] < (s_1124074005).length)) break Label14;
          var cHEX60gensym96_1124074082 = s_1124074005[i_1124074006[i_1124074006_Idx]];
          if (!((whiteSpace_1124073483[cHEX60gensym96_1124074082] != undefined))) {
          break Label13;
          }
          
          i_1124074006[i_1124074006_Idx] += 1;
        }
    };
    if (((s_1124074005).length <= i_1124074006[i_1124074006_Idx])) {
    raiseException({message: ([69,120,112,101,99,116,101,100,32,125,32,98,117,116,32,101,110,100,32,114,101,97,99,104,101,100,46,32,65,116,32,111,102,102,115,101,116,58,32] || []).concat(HEX24_385875976(i_1124074006[i_1124074006_Idx]) || []), parent: null, m_type: NTI1124073475, name: null, trace: [], up: null}, "JsonError");
    }
    
    if ((s_1124074005[i_1124074006[i_1124074006_Idx]] == 125)) {
    i_1124074006[i_1124074006_Idx] += 1;
    }
    else {
      raiseException({message: ([69,120,112,101,99,116,101,100,32,125,32,98,117,116,32,103,111,116,32] || []).concat([s_1124074005[i_1124074006[i_1124074006_Idx]]],[32,105,110,115,116,101,97,100,46,32,65,116,32,111,102,102,115,101,116,58,32] || [],HEX24_385875976(i_1124074006[i_1124074006_Idx]) || []), parent: null, m_type: NTI1124073475, name: null, trace: [], up: null}, "JsonError");
    }
    
    }
    else {
    if (((i_1124074006[i_1124074006_Idx] < (s_1124074005).length) && (s_1124074005[i_1124074006[i_1124074006_Idx]] == 91))) {
    Label15: {
        Label16: while (true) {
        if (!(i_1124074006[i_1124074006_Idx] < (s_1124074005).length)) break Label16;
          var cHEX60gensym107_1124074100 = s_1124074005[i_1124074006[i_1124074006_Idx]];
          if (!((whiteSpace_1124073483[cHEX60gensym107_1124074100] != undefined))) {
          break Label15;
          }
          
          i_1124074006[i_1124074006_Idx] += 1;
        }
    };
    if (((s_1124074005).length <= i_1124074006[i_1124074006_Idx])) {
    raiseException({message: ([69,120,112,101,99,116,101,100,32,91,32,98,117,116,32,101,110,100,32,114,101,97,99,104,101,100,46,32,65,116,32,111,102,102,115,101,116,58,32] || []).concat(HEX24_385875976(i_1124074006[i_1124074006_Idx]) || []), parent: null, m_type: NTI1124073475, name: null, trace: [], up: null}, "JsonError");
    }
    
    if ((s_1124074005[i_1124074006[i_1124074006_Idx]] == 91)) {
    i_1124074006[i_1124074006_Idx] += 1;
    }
    else {
      raiseException({message: ([69,120,112,101,99,116,101,100,32,91,32,98,117,116,32,103,111,116,32] || []).concat([s_1124074005[i_1124074006[i_1124074006_Idx]]],[32,105,110,115,116,101,97,100,46,32,65,116,32,111,102,102,115,101,116,58,32] || [],HEX24_385875976(i_1124074006[i_1124074006_Idx]) || []), parent: null, m_type: NTI1124073475, name: null, trace: [], up: null}, "JsonError");
    }
    
    Label17: {
        Label18: while (true) {
        if (!(i_1124074006[i_1124074006_Idx] < (s_1124074005).length)) break Label18;
          Label19: {
              Label20: while (true) {
              if (!(i_1124074006[i_1124074006_Idx] < (s_1124074005).length)) break Label20;
                var cHEX60gensym117_1124074118 = s_1124074005[i_1124074006[i_1124074006_Idx]];
                if (!((whiteSpace_1124073483[cHEX60gensym117_1124074118] != undefined))) {
                break Label19;
                }
                
                i_1124074006[i_1124074006_Idx] += 1;
              }
          };
          if (((i_1124074006[i_1124074006_Idx] < (s_1124074005).length) && (s_1124074005[i_1124074006[i_1124074006_Idx]] == 93))) {
          break Label17;
          }
          
          skipValue_1124074004(s_1124074005, i_1124074006, i_1124074006_Idx);
          Label21: {
              Label22: while (true) {
              if (!(i_1124074006[i_1124074006_Idx] < (s_1124074005).length)) break Label22;
                var cHEX60gensym120_1124074129 = s_1124074005[i_1124074006[i_1124074006_Idx]];
                if (!((whiteSpace_1124073483[cHEX60gensym120_1124074129] != undefined))) {
                break Label21;
                }
                
                i_1124074006[i_1124074006_Idx] += 1;
              }
          };
          if (((i_1124074006[i_1124074006_Idx] < (s_1124074005).length) && (s_1124074005[i_1124074006[i_1124074006_Idx]] == 44))) {
          i_1124074006[i_1124074006_Idx] += 1;
          }
          
        }
    };
    Label23: {
        Label24: while (true) {
        if (!(i_1124074006[i_1124074006_Idx] < (s_1124074005).length)) break Label24;
          var cHEX60gensym124_1124074145 = s_1124074005[i_1124074006[i_1124074006_Idx]];
          if (!((whiteSpace_1124073483[cHEX60gensym124_1124074145] != undefined))) {
          break Label23;
          }
          
          i_1124074006[i_1124074006_Idx] += 1;
        }
    };
    if (((s_1124074005).length <= i_1124074006[i_1124074006_Idx])) {
    raiseException({message: ([69,120,112,101,99,116,101,100,32,93,32,98,117,116,32,101,110,100,32,114,101,97,99,104,101,100,46,32,65,116,32,111,102,102,115,101,116,58,32] || []).concat(HEX24_385875976(i_1124074006[i_1124074006_Idx]) || []), parent: null, m_type: NTI1124073475, name: null, trace: [], up: null}, "JsonError");
    }
    
    if ((s_1124074005[i_1124074006[i_1124074006_Idx]] == 93)) {
    i_1124074006[i_1124074006_Idx] += 1;
    }
    else {
      raiseException({message: ([69,120,112,101,99,116,101,100,32,93,32,98,117,116,32,103,111,116,32] || []).concat([s_1124074005[i_1124074006[i_1124074006_Idx]]],[32,105,110,115,116,101,97,100,46,32,65,116,32,111,102,102,115,101,116,58,32] || [],HEX24_385875976(i_1124074006[i_1124074006_Idx]) || []), parent: null, m_type: NTI1124073475, name: null, trace: [], up: null}, "JsonError");
    }
    
    }
    else {
    if (((i_1124074006[i_1124074006_Idx] < (s_1124074005).length) && (s_1124074005[i_1124074006[i_1124074006_Idx]] == 34))) {
    var str_1124074162 = [[]];
    parseHook_1124073944(s_1124074005, i_1124074006, i_1124074006_Idx, str_1124074162, 0);
    }
    else {
    var _ = parseSymbol_1124073552(s_1124074005, i_1124074006, i_1124074006_Idx);
    }
    }}

  
}

function parseObjectInner_553648621(s_553648623, i_553648624, i_553648624_Idx, v_553648625) {
                    var Temporary10;
                    var Temporary11;
                    var Temporary12;
                    var Temporary13;

    Label1: {
        Label2: while (true) {
        if (!(i_553648624[i_553648624_Idx] < (s_553648623).length)) break Label2;
          Label3: {
              Label4: while (true) {
              if (!(i_553648624[i_553648624_Idx] < (s_553648623).length)) break Label4;
                var cHEX60gensym43_553648627 = s_553648623[i_553648624[i_553648624_Idx]];
                if (!((whiteSpace_1124073483[cHEX60gensym43_553648627] != undefined))) {
                break Label3;
                }
                
                i_553648624[i_553648624_Idx] += 1;
              }
          };
          if (((i_553648624[i_553648624_Idx] < (s_553648623).length) && (s_553648623[i_553648624[i_553648624_Idx]] == 125))) {
          break Label1;
          }
          
          var key_553648637 = [[]];
          parseHook_1124073944(s_553648623, i_553648624, i_553648624_Idx, key_553648637, 0);
          Label5: {
              Label6: while (true) {
              if (!(i_553648624[i_553648624_Idx] < (s_553648623).length)) break Label6;
                var cHEX60gensym48_553648639 = s_553648623[i_553648624[i_553648624_Idx]];
                if (!((whiteSpace_1124073483[cHEX60gensym48_553648639] != undefined))) {
                break Label5;
                }
                
                i_553648624[i_553648624_Idx] += 1;
              }
          };
          if (((s_553648623).length <= i_553648624[i_553648624_Idx])) {
          raiseException({message: ([69,120,112,101,99,116,101,100,32,58,32,98,117,116,32,101,110,100,32,114,101,97,99,104,101,100,46,32,65,116,32,111,102,102,115,101,116,58,32] || []).concat(HEX24_385875976(i_553648624[i_553648624_Idx]) || []), parent: null, m_type: NTI1124073475, name: null, trace: [], up: null}, "JsonError");
          }
          
          if ((s_553648623[i_553648624[i_553648624_Idx]] == 58)) {
          i_553648624[i_553648624_Idx] += 1;
          }
          else {
            raiseException({message: ([69,120,112,101,99,116,101,100,32,58,32,98,117,116,32,103,111,116,32] || []).concat([s_553648623[i_553648624[i_553648624_Idx]]],[32,105,110,115,116,101,97,100,46,32,65,116,32,111,102,102,115,101,116,58,32] || [],HEX24_385875976(i_553648624[i_553648624_Idx]) || []), parent: null, m_type: NTI1124073475, name: null, trace: [], up: null}, "JsonError");
          }
          
          Label7: {
            Label8: {
                Label9: while (true) {
                if (!true) break Label9;
                    if (eqStrings([116,105,116,108,101], key_553648637[0])) Temporary10 = true; else {                      Temporary10 = eqStrings([116,105,116,108,101], key_553648637[0]);                    }                  if (Temporary10) {
                  var v2_553648669 = [[]];
                  parseHook_1124073944(s_553648623, i_553648624, i_553648624_Idx, v2_553648669, 0);
                  v_553648625.title = nimCopy(null, v2_553648669[0], NTI33554449);
                  break Label7;
                  }
                  
                    if (eqStrings([115,108,117,103], key_553648637[0])) Temporary11 = true; else {                      Temporary11 = eqStrings([115,108,117,103], key_553648637[0]);                    }                  if (Temporary11) {
                  var v2_553648672 = [[]];
                  parseHook_1124073944(s_553648623, i_553648624, i_553648624_Idx, v2_553648672, 0);
                  v_553648625.slug = nimCopy(null, v2_553648672[0], NTI33554449);
                  break Label7;
                  }
                  
                    if (eqStrings([99,111,110,116,101,110,116,84,111,107,101,110,115], key_553648637[0])) Temporary12 = true; else {                      Temporary12 = eqStrings([99,111,110,116,101,110,116,95,116,111,107,101,110,115], key_553648637[0]);                    }                  if (Temporary12) {
                  var v2_553648675 = [[]];
                  parseHook_553648676(s_553648623, i_553648624, i_553648624_Idx, v2_553648675, 0);
                  v_553648625.contentTokens = nimCopy(null, v2_553648675[0], NTI553648133);
                  break Label7;
                  }
                  
                    if (eqStrings([100,105,115,112,108,97,121,67,111,110,116,101,110,116], key_553648637[0])) Temporary13 = true; else {                      Temporary13 = eqStrings([100,105,115,112,108,97,121,95,99,111,110,116,101,110,116], key_553648637[0]);                    }                  if (Temporary13) {
                  var v2_553648751 = [[]];
                  parseHook_1124073944(s_553648623, i_553648624, i_553648624_Idx, v2_553648751, 0);
                  v_553648625.displayContent = nimCopy(null, v2_553648751[0], NTI33554449);
                  break Label7;
                  }
                  
                  break Label8;
                }
            };
            skipValue_1124074004(s_553648623, i_553648624, i_553648624_Idx);
          };
          Label14: {
              Label15: while (true) {
              if (!(i_553648624[i_553648624_Idx] < (s_553648623).length)) break Label15;
                var cHEX60gensym92_553648753 = s_553648623[i_553648624[i_553648624_Idx]];
                if (!((whiteSpace_1124073483[cHEX60gensym92_553648753] != undefined))) {
                break Label14;
                }
                
                i_553648624[i_553648624_Idx] += 1;
              }
          };
          if (((i_553648624[i_553648624_Idx] < (s_553648623).length) && (s_553648623[i_553648624[i_553648624_Idx]] == 44))) {
          i_553648624[i_553648624_Idx] += 1;
          }
          else {
            break Label1;
          }
          
        }
    };

  
}

function parseHook_553648569(s_553648571, i_553648572, i_553648572_Idx, v_553648573) {
  BeforeRet: {
    Label1: {
        Label2: while (true) {
        if (!(i_553648572[i_553648572_Idx] < (s_553648571).length)) break Label2;
          var cHEX60gensym25_553648575 = s_553648571[i_553648572[i_553648572_Idx]];
          if (!((whiteSpace_1124073483[cHEX60gensym25_553648575] != undefined))) {
          break Label1;
          }
          
          i_553648572[i_553648572_Idx] += 1;
        }
    };
    if (((((((i_553648572[i_553648572_Idx] + 3) < (s_553648571).length) && (s_553648571[(i_553648572[i_553648572_Idx] + 0)] == 110)) && (s_553648571[(i_553648572[i_553648572_Idx] + 1)] == 117)) && (s_553648571[(i_553648572[i_553648572_Idx] + 2)] == 108)) && (s_553648571[(i_553648572[i_553648572_Idx] + 3)] == 108))) {
    i_553648572[i_553648572_Idx] += 4;
    break BeforeRet;
    }
    
    Label3: {
        Label4: while (true) {
        if (!(i_553648572[i_553648572_Idx] < (s_553648571).length)) break Label4;
          var cHEX60gensym33_553648590 = s_553648571[i_553648572[i_553648572_Idx]];
          if (!((whiteSpace_1124073483[cHEX60gensym33_553648590] != undefined))) {
          break Label3;
          }
          
          i_553648572[i_553648572_Idx] += 1;
        }
    };
    if (((s_553648571).length <= i_553648572[i_553648572_Idx])) {
    raiseException({message: ([69,120,112,101,99,116,101,100,32,123,32,98,117,116,32,101,110,100,32,114,101,97,99,104,101,100,46,32,65,116,32,111,102,102,115,101,116,58,32] || []).concat(HEX24_385875976(i_553648572[i_553648572_Idx]) || []), parent: null, m_type: NTI1124073475, name: null, trace: [], up: null}, "JsonError");
    }
    
    if ((s_553648571[i_553648572[i_553648572_Idx]] == 123)) {
    i_553648572[i_553648572_Idx] += 1;
    }
    else {
      raiseException({message: ([69,120,112,101,99,116,101,100,32,123,32,98,117,116,32,103,111,116,32] || []).concat([s_553648571[i_553648572[i_553648572_Idx]]],[32,105,110,115,116,101,97,100,46,32,65,116,32,111,102,102,115,101,116,58,32] || [],HEX24_385875976(i_553648572[i_553648572_Idx]) || []), parent: null, m_type: NTI1124073475, name: null, trace: [], up: null}, "JsonError");
    }
    
    parseObjectInner_553648621(s_553648571, i_553648572, i_553648572_Idx, v_553648573);
    Label5: {
        Label6: while (true) {
        if (!(i_553648572[i_553648572_Idx] < (s_553648571).length)) break Label6;
          var cHEX60gensym97_553648771 = s_553648571[i_553648572[i_553648572_Idx]];
          if (!((whiteSpace_1124073483[cHEX60gensym97_553648771] != undefined))) {
          break Label5;
          }
          
          i_553648572[i_553648572_Idx] += 1;
        }
    };
    if (((s_553648571).length <= i_553648572[i_553648572_Idx])) {
    raiseException({message: ([69,120,112,101,99,116,101,100,32,125,32,98,117,116,32,101,110,100,32,114,101,97,99,104,101,100,46,32,65,116,32,111,102,102,115,101,116,58,32] || []).concat(HEX24_385875976(i_553648572[i_553648572_Idx]) || []), parent: null, m_type: NTI1124073475, name: null, trace: [], up: null}, "JsonError");
    }
    
    if ((s_553648571[i_553648572[i_553648572_Idx]] == 125)) {
    i_553648572[i_553648572_Idx] += 1;
    }
    else {
      raiseException({message: ([69,120,112,101,99,116,101,100,32,125,32,98,117,116,32,103,111,116,32] || []).concat([s_553648571[i_553648572[i_553648572_Idx]]],[32,105,110,115,116,101,97,100,46,32,65,116,32,111,102,102,115,101,116,58,32] || [],HEX24_385875976(i_553648572[i_553648572_Idx]) || []), parent: null, m_type: NTI1124073475, name: null, trace: [], up: null}, "JsonError");
    }
    
  };

  
}

function parseHook_553648534(s_553648536, i_553648537, i_553648537_Idx, v_553648538, v_553648538_Idx) {
    Label1: {
        Label2: while (true) {
        if (!(i_553648537[i_553648537_Idx] < (s_553648536).length)) break Label2;
          var cHEX60gensym11_553648540 = s_553648536[i_553648537[i_553648537_Idx]];
          if (!((whiteSpace_1124073483[cHEX60gensym11_553648540] != undefined))) {
          break Label1;
          }
          
          i_553648537[i_553648537_Idx] += 1;
        }
    };
    if (((s_553648536).length <= i_553648537[i_553648537_Idx])) {
    raiseException({message: ([69,120,112,101,99,116,101,100,32,91,32,98,117,116,32,101,110,100,32,114,101,97,99,104,101,100,46,32,65,116,32,111,102,102,115,101,116,58,32] || []).concat(HEX24_385875976(i_553648537[i_553648537_Idx]) || []), parent: null, m_type: NTI1124073475, name: null, trace: [], up: null}, "JsonError");
    }
    
    if ((s_553648536[i_553648537[i_553648537_Idx]] == 91)) {
    i_553648537[i_553648537_Idx] += 1;
    }
    else {
      raiseException({message: ([69,120,112,101,99,116,101,100,32,91,32,98,117,116,32,103,111,116,32] || []).concat([s_553648536[i_553648537[i_553648537_Idx]]],[32,105,110,115,116,101,97,100,46,32,65,116,32,111,102,102,115,101,116,58,32] || [],HEX24_385875976(i_553648537[i_553648537_Idx]) || []), parent: null, m_type: NTI1124073475, name: null, trace: [], up: null}, "JsonError");
    }
    
    Label3: {
        Label4: while (true) {
        if (!(i_553648537[i_553648537_Idx] < (s_553648536).length)) break Label4;
          Label5: {
              Label6: while (true) {
              if (!(i_553648537[i_553648537_Idx] < (s_553648536).length)) break Label6;
                var cHEX60gensym21_553648558 = s_553648536[i_553648537[i_553648537_Idx]];
                if (!((whiteSpace_1124073483[cHEX60gensym21_553648558] != undefined))) {
                break Label5;
                }
                
                i_553648537[i_553648537_Idx] += 1;
              }
          };
          if (((i_553648537[i_553648537_Idx] < (s_553648536).length) && (s_553648536[i_553648537[i_553648537_Idx]] == 93))) {
          break Label3;
          }
          
          var element_553648568 = [({title: [], slug: [], contentTokens: [], displayContent: []})];
          parseHook_553648569(s_553648536, i_553648537, i_553648537_Idx, element_553648568[0]);
          var Temporary7 = nimCopy(null, element_553648568[0], NTI553648132);
          v_553648538[v_553648538_Idx].push(Temporary7);;
          Label8: {
              Label9: while (true) {
              if (!(i_553648537[i_553648537_Idx] < (s_553648536).length)) break Label9;
                var cHEX60gensym107_553648793 = s_553648536[i_553648537[i_553648537_Idx]];
                if (!((whiteSpace_1124073483[cHEX60gensym107_553648793] != undefined))) {
                break Label8;
                }
                
                i_553648537[i_553648537_Idx] += 1;
              }
          };
          if (((i_553648537[i_553648537_Idx] < (s_553648536).length) && (s_553648536[i_553648537[i_553648537_Idx]] == 44))) {
          i_553648537[i_553648537_Idx] += 1;
          }
          else {
            break Label3;
          }
          
        }
    };
    Label10: {
        Label11: while (true) {
        if (!(i_553648537[i_553648537_Idx] < (s_553648536).length)) break Label11;
          var cHEX60gensym112_553648809 = s_553648536[i_553648537[i_553648537_Idx]];
          if (!((whiteSpace_1124073483[cHEX60gensym112_553648809] != undefined))) {
          break Label10;
          }
          
          i_553648537[i_553648537_Idx] += 1;
        }
    };
    if (((s_553648536).length <= i_553648537[i_553648537_Idx])) {
    raiseException({message: ([69,120,112,101,99,116,101,100,32,93,32,98,117,116,32,101,110,100,32,114,101,97,99,104,101,100,46,32,65,116,32,111,102,102,115,101,116,58,32] || []).concat(HEX24_385875976(i_553648537[i_553648537_Idx]) || []), parent: null, m_type: NTI1124073475, name: null, trace: [], up: null}, "JsonError");
    }
    
    if ((s_553648536[i_553648537[i_553648537_Idx]] == 93)) {
    i_553648537[i_553648537_Idx] += 1;
    }
    else {
      raiseException({message: ([69,120,112,101,99,116,101,100,32,93,32,98,117,116,32,103,111,116,32] || []).concat([s_553648536[i_553648537[i_553648537_Idx]]],[32,105,110,115,116,101,97,100,46,32,65,116,32,111,102,102,115,101,116,58,32] || [],HEX24_385875976(i_553648537[i_553648537_Idx]) || []), parent: null, m_type: NTI1124073475, name: null, trace: [], up: null}, "JsonError");
    }
    

  
}

function fromJson_553648527(s_553648530) {
  var result_553648532 = [[]];

    var i_553648533 = [0];
    parseHook_553648534(s_553648530, i_553648533, 0, result_553648532, 0);

  return result_553648532[0];

}

function onDOMLoaded(e_553648521) {
    rawEcho([108,111,97,100,101,100]);
    var seachContainer_553648522 = document.getElementById("search-container");
    var searchResults_553648523 = document.createElement("div");
    searchResults_553648523.id = "search-results";
    var seachInp_553648524 = document.createElement("input");
    seachInp_553648524.setAttribute("type", "text");
    seachInp_553648524.setAttribute("placeholder", "Search");
    var dbString_553648525 = null;
        var request = new XMLHttpRequest();
    request.open("GET", "search.json", false);
    request.send(null);
    dbString_553648525 = request.responseText
  
    var s_553648526 = cstrToNimstr(dbString_553648525);
    searchDB_553648145[0] = nimCopy(null, fromJson_553648527(s_553648526), NTI553648134);
    seachInp_553648524.addEventListener("keyup", onInput, false);
    seachContainer_553648522.appendChild(seachInp_553648524);
    seachContainer_553648522.appendChild(searchResults_553648523);

  
}
var searchDB_553648145 = [[]];
window.addEventListener("DOMContentLoaded", onDOMLoaded, false);
